# Kubernetes ConfigMaps for AI Trading Platform
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: trading-platform
data:
  # Application Configuration
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # API Configuration
  API_VERSION: "v1"
  API_TIMEOUT: "30"
  
  # CORS Configuration
  CORS_ORIGINS: "https://tradingplatform.com,https://app.tradingplatform.com,https://admin.tradingplatform.com"
  
  # Domain Configuration
  DOMAIN: "tradingplatform.com"
  API_DOMAIN: "api.tradingplatform.com"
  ADMIN_DOMAIN: "admin.tradingplatform.com"
  FRONTEND_DOMAIN: "app.tradingplatform.com"
  
  # Rate Limiting
  RATE_LIMIT_REQUESTS_PER_MINUTE: "30"
  RATE_LIMIT_LOGIN_ATTEMPTS_PER_IP: "5"
  
  # Session Configuration
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  
  # Database Configuration
  POOL_SIZE: "20"
  MAX_OVERFLOW: "40"
  
  # Performance Settings
  MAX_WORKERS: "8"
  
  # Feature Flags
  ENABLE_REAL_TRADING: "true"
  ENABLE_AUTO_TRADING: "true"
  ENABLE_ML_PREDICTIONS: "true"
  ENABLE_NEWS_SENTIMENT: "true"
  
  # Health Checks
  HEALTH_CHECK_INTERVAL: "30"
  
  # Algorithm Configuration
  ALGORITHM: "HS256"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: trading-platform
data:
  POSTGRES_DB: "trading_platform"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  
  # Connection settings
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "40"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: trading-platform
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_MAX_CONNECTIONS: "100"
  REDIS_SOCKET_TIMEOUT: "30"
  REDIS_SOCKET_CONNECT_TIMEOUT: "30"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: trading-platform
data:
  INFLUXDB_HOST: "influxdb-service"
  INFLUXDB_PORT: "8086"
  INFLUXDB_ORG: "trading-platform-prod"
  INFLUXDB_BUCKET: "market-data-prod"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: trading-platform
data:
  # Monitoring settings
  DATADOG_ENABLED: "false"
  NEW_RELIC_ENABLED: "false"
  PROMETHEUS_ENABLED: "true"
  
  # Metrics
  METRICS_PORT: "9090"
  METRICS_PATH: "/metrics"
  
  # Logging
  LOG_AGGREGATION: "true"
  LOG_RETENTION_DAYS: "30"