# Prometheus configuration for Trading Platform monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'trading-platform'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Trading Platform API Server
  - job_name: 'trading-platform-api'
    static_configs:
      - targets: ['trading-api:8000']
    metrics_path: '/monitoring/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'trading-api'
      - target_label: service
        replacement: 'trading-platform'
      - target_label: component
        replacement: 'api'

  # Strategy Engine Metrics
  - job_name: 'strategy-engine'
    static_configs:
      - targets: ['strategy-engine:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: 'trading-platform'
      - target_label: component
        replacement: 'strategy-engine'

  # ML Service Metrics
  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 60s
    relabel_configs:
      - target_label: service
        replacement: 'trading-platform'
      - target_label: component
        replacement: 'ml-service'

  # Data Service Metrics
  - job_name: 'data-service'
    static_configs:
      - targets: ['data-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: 'trading-platform'
      - target_label: component
        replacement: 'data-service'

  # Database Metrics (PostgreSQL Exporter)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: 'trading-platform'
      - target_label: component
        replacement: 'database'

  # Redis Metrics (Redis Exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: 'trading-platform'
      - target_label: component
        replacement: 'cache'

  # InfluxDB Metrics
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    metrics_path: '/metrics'
    scrape_interval: 60s
    relabel_configs:
      - target_label: service
        replacement: 'trading-platform'
      - target_label: component
        replacement: 'timeseries-db'

  # Message Queue Metrics (RabbitMQ)
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    scrape_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: 'trading-platform'
      - target_label: component
        replacement: 'message-queue'

  # System Metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: 'trading-platform'
      - target_label: component
        replacement: 'system'

  # Cadvisor (Container Metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: 'trading-platform'
      - target_label: component
        replacement: 'containers'

  # Frontend Metrics (Nginx/React)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 60s
    relabel_configs:
      - target_label: service
        replacement: 'trading-platform'
      - target_label: component
        replacement: 'frontend'

  # Health Check Endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets: 
          - 'trading-api:8000'
          - 'strategy-engine:8001'
          - 'ml-service:8002'
          - 'data-service:8003'
    metrics_path: '/health'
    scrape_interval: 15s
    params:
      format: ['prometheus']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: __name__
        replacement: 'service_up'

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

# Remote write configuration (for long-term storage)
remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Remote read configuration
remote_read:
  - url: "http://influxdb:8086/api/v1/prom/read?db=prometheus"